// This file is auto-generated by the backend-json-to-ts script.
// Do not edit this file directly.

export interface UserProfile {
    /**
     * The user's display name.
     */
    displayName: string;
    /**
     * The user's unique username.
     */
    username?: string;
    /**
     * The user's email address.
     */
    email: string;
    /**
     * URL of the user's profile picture.
     */
    photoURL?: string;
    /**
     * The user's current level.
     */
    level?: number;
    /**
     * The user's current practice streak.
     */
    streak?: number;
    /**
     * The last time the user's practice streak was updated.
     */
    lastStreakUpdate?: string | null;
    /**
     * List of achievements unlocked by the user.
     */
    achievements?: string[];
    /**
     * Whether the user has learning reminders enabled.
     */
    reminders?: boolean;
    /**
     * Whether the user wants to receive weekly email summaries.
     */
    emailNotifications?: boolean;
    /**
     * The user's preferred time for learning reminders (e.g., '19:00').
     */
    reminderTime?: string;
    /**
     * Number of lives the user has.
     */
    lives?: number;
    /**
     * The last time a life was regenerated.
     */
    lastLifeUpdate?: string;
    /**
     * The user's unique ID from Firebase Authentication.
     */
    firebaseUid: string;
    /**
     * Object containing user's progress in courses.
     */
    progress?: {
        [key: string]: {
            /**
             * Array of completed lesson IDs.
             */
            completedLessons?: string[];
            /**
             * Array of unlocked lesson IDs.
             */
            unlockedLessons?: string[];
        };
    };
    /**
     * Firebase Cloud Messaging token for push notifications.
     */
    fcmToken?: string | null;
    createdAt?: Date;
    /**
     * Whether the user has didactic mode enabled.
     */
    didacticMode?: boolean;
    /**
     * Whether the user has the daily challenge enabled.
     */
    dailyChallenge?: boolean;
}
export interface Course {
    id: string;
    title?: string;
    description?: string;
    /**
     * Name of the icon component (e.g., 'PythonIcon').
     */
    icon?: string;
    /**
     * ID of the placeholder image for the course.
     */
    imageId?: string;
}
/**
 * A module within a course, containing lessons.
 */
export interface Module {
    id: string;
    title?: string;
    type?: "theory" | "quiz";
    /**
     * ID of the corresponding theory or quiz.
     */
    contentId?: string;
    /**
     * Duration in minutes.
     */
    duration?: number;
    /**
     * Order of the module within the course.
     */
    order?: number;
}
/**
 * The content for a theory lesson, composed of pages.
 */
export interface Theory {
    id: string;
    title?: string;
}
/**
 * A single page of content within a theory lesson.
 */
export interface TheoryPage {
    id: string;
    /**
     * The markdown content of the page.
     */
    content?: string;
    /**
     * The order of the page within the lesson.
     */
    order?: number;
    /**
     * The title of the page within the lesson.
     */
    title?: string;
}
