
// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDyzuwWnF29e3uDfAZolx00Xf4pZA-ol5w",
  authDomain: "studio-3220804462-4f87a.firebaseapp.com",
  projectId: "studio-3220804462-4f87a",
  storageBucket: "studio-3220804462-4f87a.appspot.com",
  messagingSenderId: "81912450805",
  appId: "1:81912450805:web:ce5ae7e420bebd9b7affbc",
};
