
// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBjh8_egzgMzNCbifozE9rYoV1VNC9MlGk",
  authDomain: "studio-3220804462-a959d.firebaseapp.com",
  projectId: "studio-3220804462-a959d",
  storageBucket: "studio-3220804462-a959d.appspot.com",
  messagingSenderId: "343443135639",
  appId: "1:343443135639:web:19791dd380c7ae78919dd2",
};
